### ISSUE TITLE
Initial date values

### ISSUE THREAD

**Issue by lexmarionB** [gravitano/vue-date-range-picker#12]
If the bound v-model variable contains a value consisting of time & date, it is ignored. Would be better to have it applied on the picker on initialization to provide a preset.

**Comment by gravitano** [comment]
Is this issue already resolved?

**Comment by Cur1yJ** [comment]
No. I passed the start & end date through the options instead.

**Comment by lexmarionb** [comment]
No. I passed the start & end date through the options instead.
